/**
 * Điền cột HÌNH cho mọi sheet từ vựng trong bảng tính FLASHCARD.
 *
 * Cách dùng: mở trình biên tập Apps Script, dán tệp này vào một tệp mới tên
 * DienCotHinh.gs, chọn hàm dienCotHinh rồi bấm Chạy. Chạy lại bao nhiêu lần
 * cũng được.
 *
 * Quy tắc an toàn:
 *  - Ô nào đã có hình thì GIỮ NGUYÊN. Hình anh tự điền tay không bao giờ bị đè.
 *  - Sheet Starters bị bỏ qua: ứng dụng đã có bộ hình vẽ sẵn đẹp hơn cho bộ này
 *    (màu sắc, số đếm có chấm để đếm, giới từ, đại từ) và cột HÌNH sẽ lấn át nó.
 *  - Chỉ ghi vào cột HÌNH, không đụng tới cột nào khác.
 *
 * Tra theo cột NGHĨA tiếng Việt nên dùng chung được cho mọi thứ tiếng.
 */

var ANH_SANG_HINH = {
  'apple': '🍎',
  'arm': '💪',
  'baby': '👶',
  'bag': '🎒',
  'ball': '⚽',
  'banana': '🍌',
  'bed': '🛏️',
  'bird': '🐦',
  'book': '📕',
  'box': '📦',
  'boy': '👦',
  'bread': '🍞',
  'cake': '🎂',
  'candy': '🍬',
  'cat': '🐱',
  'chair': '🪑',
  'chicken': '🐔',
  'clock': '🕐',
  'computer': '💻',
  'cookie': '🍪',
  'cow': '🐄',
  'dog': '🐶',
  'door': '🚪',
  'duck': '🦆',
  'ear': '👂',
  'egg': '🥚',
  'elephant': '🐘',
  'eye': '👁️',
  'family': '👨‍👩‍👧‍👦',
  'fish': '🐟',
  'flower': '🌷',
  'foot': '🦶',
  'frog': '🐸',
  'girl': '👧',
  'goat': '🐐',
  'grape': '🍇',
  'hand': '✋',
  'hat': '🎩',
  'head': '🧠',
  'horse': '🐴',
  'house': '🏡',
  'juice': '🍹',
  'key': '🔑',
  'kitchen': '🍳',
  'lamp': '💡',
  'leg': '🦵',
  'lemon': '🍋',
  'lion': '🦁',
  'mango': '🥭',
  'meat': '🍖',
  'milk': '🥛',
  'monkey': '🐵',
  'mountain': '⛰️',
  'mouse': '🐭',
  'mouth': '👄',
  'nose': '👃',
  'orange': '🍊',
  'pear': '🍐',
  'pen': '🖊️',
  'pencil': '✏️',
  'pig': '🐷',
  'rain': '🌧️',
  'rice': '🍚',
  'river': '🛶',
  'school': '🏫',
  'sheep': '🐑',
  'shirt': '👔',
  'shoes': '👟',
  'snow': '❄️',
  'soup': '🍲',
  'star': '⭐',
  'sun': '☀️',
  'table': '🪑',
  'teacher': '👩‍🏫',
  'tiger': '🐯',
  'tooth': '🦷',
  'toy': '🧸',
  'train': '🚆',
  'tree': '🌳',
  'water': '💧',
  'watermelon': '🍉',
  'window': '🪟',
  'zebra': '🦓'
};

var NGHIA_SANG_HINH = {
  'mèo': '🐱',
  'chó': '🐶',
  'chim': '🐦',
  'cá': '🐟',
  'gà': '🐔',
  'vịt': '🦆',
  'bò': '🐄',
  'trâu': '🐃',
  'lợn': '🐷',
  'heo': '🐷',
  'dê': '🐐',
  'cừu': '🐑',
  'ngựa': '🐴',
  'voi': '🐘',
  'hổ': '🐯',
  'cọp': '🐯',
  'sư tử': '🦁',
  'gấu': '🐻',
  'khỉ': '🐵',
  'chuột': '🐭',
  'thỏ': '🐰',
  'ếch': '🐸',
  'rắn': '🐍',
  'rùa': '🐢',
  'cá sấu': '🐊',
  'cá voi': '🐳',
  'cá heo': '🐬',
  'cá mập': '🦈',
  'bạch tuộc': '🐙',
  'cua': '🦀',
  'tôm': '🦐',
  'ong': '🐝',
  'bướm': '🦋',
  'kiến': '🐜',
  'nhện': '🕷️',
  'muỗi': '🦟',
  'côn trùng': '🐞',
  'sâu': '🐛',
  'hươu cao cổ': '🦒',
  'ngựa vằn': '🦓',
  'lạc đà': '🐫',
  'chuột túi': '🦘',
  'cáo': '🦊',
  'sói': '🐺',
  'nai': '🦌',
  'gấu trúc': '🐼',
  'khủng long': '🦕',
  'chim cánh cụt': '🐧',
  'đại bàng': '🦅',
  'cú': '🦉',
  'công': '🦚',
  'vẹt': '🦜',
  'thiên nga': '🦢',
  'động vật': '🐾',
  'thú cưng': '🐾',
  'chuồng': '🏚️',
  'tổ': '🪺',
  'lông': '🪶',
  'táo': '🍎',
  'chuối': '🍌',
  'cam': '🍊',
  'nho': '🍇',
  'dâu': '🍓',
  'dưa hấu': '🍉',
  'xoài': '🥭',
  'dứa': '🍍',
  'thơm': '🍍',
  'đào': '🍑',
  'lê': '🍐',
  'chanh': '🍋',
  'dừa': '🥥',
  'kiwi': '🥝',
  'cà chua': '🍅',
  'cà rốt': '🥕',
  'khoai tây': '🥔',
  'ngô': '🌽',
  'bắp': '🌽',
  'ớt': '🌶️',
  'dưa chuột': '🥒',
  'nấm': '🍄',
  'rau': '🥬',
  'rau củ': '🥕',
  'trái cây': '🍎',
  'hoa quả': '🍎',
  'hành': '🧅',
  'tỏi': '🧄',
  'bánh mì': '🍞',
  'bánh ngọt': '🎂',
  'bánh quy': '🍪',
  'bánh kem': '🍰',
  'kẹo': '🍬',
  'sô cô la': '🍫',
  'kem': '🍦',
  'mật ong': '🍯',
  'trứng': '🥚',
  'thịt': '🍖',
  'cơm': '🍚',
  'gạo': '🌾',
  'mì': '🍜',
  'phở': '🍜',
  'súp': '🍲',
  'canh': '🍲',
  'salad': '🥗',
  'phô mai': '🧀',
  'bơ': '🧈',
  'muối': '🧂',
  'bánh mì kẹp': '🥪',
  'pizza': '🍕',
  'hamburger': '🍔',
  'khoai tây chiên': '🍟',
  'sữa': '🥛',
  'nước': '💧',
  'nước ép': '🍹',
  'trà': '🍵',
  'cà phê': '☕',
  'bia': '🍺',
  'rượu': '🍷',
  'đồ ăn': '🍽️',
  'thức ăn': '🍽️',
  'bữa ăn': '🍽️',
  'bữa sáng': '🍳',
  'bữa trưa': '🍱',
  'bữa tối': '🍽️',
  'món tráng miệng': '🍮',
  'đường': '🛣️',
  'bột': '🌾',
  'bột mì': '🌾',
  'dầu': '🛢️',
  'mắt': '👁️',
  'tai': '👂',
  'mũi': '👃',
  'miệng': '👄',
  'răng': '🦷',
  'lưỡi': '👅',
  'tay': '✋',
  'bàn tay': '✋',
  'cánh tay': '💪',
  'chân': '🦵',
  'bàn chân': '🦶',
  'tóc': '💇',
  'mặt': '🙂',
  'khuôn mặt': '🙂',
  'đầu': '🧠',
  'tim': '❤️',
  'não': '🧠',
  'xương': '🦴',
  'da': '🤲',
  'máu': '🩸',
  'cơ thể': '🧍',
  'ngón tay': '👆',
  'vai': '🤷',
  'lưng': '🔙',
  'cổ': '👔',
  'bụng': '🫃',
  'người': '🧑',
  'đàn ông': '👨',
  'phụ nữ': '👩',
  'con trai': '👦',
  'bé trai': '👦',
  'con gái': '👧',
  'bé gái': '👧',
  'em bé': '👶',
  'trẻ em': '🧒',
  'trẻ con': '🧒',
  'bố': '👨‍👧',
  'cha': '👨‍👧',
  'mẹ': '👩‍👧',
  'má': '👩‍👧',
  'ông': '👴',
  'bà': '👵',
  'anh': '👦',
  'chị': '👧',
  'em': '🧒',
  'gia đình': '👨‍👩‍👧‍👦',
  'bạn': '🤝',
  'bạn bè': '🤝',
  'vợ': '👰',
  'chồng': '🤵',
  'con': '🧒',
  'cháu': '🧒',
  'cô': '👩‍🦰',
  'dì': '👩‍🦰',
  'chú': '👨',
  'bác': '👨',
  'cậu': '👨',
  'họ hàng': '👪',
  'hàng xóm': '🏘️',
  'giáo viên': '👩‍🏫',
  'thầy': '👨‍🏫',
  'học sinh': '🎓',
  'sinh viên': '🎓',
  'bác sĩ': '👨‍⚕️',
  'y tá': '👩‍⚕️',
  'nông dân': '👨‍🌾',
  'công nhân': '👷',
  'kỹ sư': '👷',
  'cảnh sát': '👮',
  'lính cứu hỏa': '🚒',
  'đầu bếp': '👨‍🍳',
  'ca sĩ': '🎤',
  'họa sĩ': '🎨',
  'nghệ sĩ': '🎭',
  'nhà khoa học': '🥼',
  'phi công': '🧑‍✈️',
  'thủy thủ': '⛵',
  'tài xế': '🚖',
  'thợ máy': '🔧',
  'nhà báo': '📰',
  'luật sư': '⚖️',
  'khách hàng': '🧑‍💼',
  'nhân viên': '🧑‍💼',
  'giám đốc': '🧑‍💼',
  'chủ': '🔑',
  'đám đông': '👥',
  'dân số': '👥',
  'thành viên': '🧑‍🤝‍🧑',
  'đội': '👥',
  'áo': '👕',
  'áo sơ mi': '👔',
  'áo phông': '👕',
  'áo khoác': '🧥',
  'áo len': '🧶',
  'quần': '👖',
  'quần dài': '👖',
  'quần đùi': '🩳',
  'váy': '👗',
  'chân váy': '👗',
  'giày': '👟',
  'dép': '🩴',
  'tất': '🧦',
  'vớ': '🧦',
  'mũ': '🎩',
  'nón': '👒',
  'khăn': '🧣',
  'khăn quàng': '🧣',
  'găng tay': '🧤',
  'kính': '👓',
  'nhẫn': '💍',
  'đồng hồ': '⌚',
  'túi': '👜',
  'ba lô': '🎒',
  'cặp': '✌️',
  'ví': '👛',
  'trang sức': '💎',
  'đồng phục': '👔',
  'thời trang': '👗',
  'quần áo': '👕',
  'nhà': '🏠',
  'ngôi nhà': '🏡',
  'căn hộ': '🏢',
  'phòng': '🚪',
  'phòng ngủ': '🛌',
  'phòng khách': '🛋️',
  'phòng tắm': '🛁',
  'nhà bếp': '🍳',
  'bếp': '🍳',
  'cửa': '🚪',
  'cửa sổ': '🪟',
  'tường': '🧱',
  'mái nhà': '🏠',
  'sàn': '🏢',
  'cầu thang': '🪜',
  'giường': '🛏️',
  'bàn': '🪑',
  'ghế': '🪑',
  'ghế sô pha': '🛋️',
  'tủ': '🗄️',
  'kệ': '📚',
  'gương': '🖼️',
  'đèn': '💡',
  'tủ lạnh': '🧊',
  'lò nướng': '🍞',
  'chăn': '🛏️',
  'gối': '🛏️',
  'thảm': '🧶',
  'chìa khóa': '🔑',
  'ổ khóa': '🔒',
  'đĩa': '🍽️',
  'bát': '🥣',
  'chén': '🥣',
  'cốc': '🥛',
  'ly': '🥛',
  'thìa': '🥄',
  'muỗng': '🥄',
  'dĩa': '🍴',
  'nĩa': '🍴',
  'dao': '🔪',
  'nồi': '🍲',
  'chảo': '🍳',
  'chai': '🍾',
  'hộp': '📦',
  'giỏ': '🧺',
  'thùng rác': '🗑️',
  'xà phòng': '🧼',
  'bàn chải': '🖌️',
  'khăn tắm': '🧻',
  'quạt': '🌀',
  'điều hòa': '❄️',
  'máy giặt': '🧺',
  'ban công': '🏨',
  'vườn': '🌻',
  'hàng rào': '🚧',
  'sân': '🏡',
  'ga ra': '🚗',
  'sách': '📕',
  'vở': '📓',
  'giấy': '📄',
  'bút': '🖊️',
  'bút chì': '✏️',
  'tẩy': '🧽',
  'cục tẩy': '🧽',
  'thước': '📏',
  'thước kẻ': '📏',
  'bảng': '🗒️',
  'lớp': '🏫',
  'lớp học': '🏫',
  'trường': '🏫',
  'trường học': '🏫',
  'bài tập': '📝',
  'bài học': '📖',
  'bài kiểm tra': '📝',
  'kỳ thi': '📝',
  'điểm': '💯',
  'điểm số': '💯',
  'từ điển': '📖',
  'thư viện': '📚',
  'bút màu': '🖍️',
  'kéo': '✂️',
  'keo': '🧴',
  'cặp sách': '🎒',
  'bảng đen': '🗒️',
  'phấn': '🖍️',
  'tập vở': '📓',
  'nhật ký': '📔',
  'tạp chí': '📙',
  'báo': '📰',
  'thư': '✉️',
  'phong bì': '✉️',
  'tem': '📮',
  'bưu thiếp': '📮',
  'chữ': '🔤',
  'chữ cái': '🔤',
  'từ': '🔤',
  'câu': '📝',
  'trang': '📄',
  'sổ': '📓',
  'lịch': '📅',
  'giáo dục': '🏫',
  'kiến thức': '📚',
  'khoa học': '🔬',
  'toán': '🧮',
  'lịch sử': '📜',
  'địa lý': '🗺️',
  'sinh học': '🧬',
  'hóa học': '⚗️',
  'vật lý': '⚛️',
  'ngôn ngữ': '🗣️',
  'văn học': '📚',
  'thí nghiệm': '🧪',
  'phòng thí nghiệm': '🔬',
  'nghiên cứu': '🔬',
  'kính hiển vi': '🔬',
  'cây': '🌳',
  'hoa': '🌷',
  'lá': '🍃',
  'cỏ': '🌱',
  'hạt': '🌰',
  'rễ': '🌱',
  'rừng': '🌲',
  'núi': '⛰️',
  'đồi': '🌄',
  'sông': '🛶',
  'biển': '🌊',
  'đại dương': '🌊',
  'hồ': '🏞️',
  'suối': '💦',
  'đảo': '🏝️',
  'hòn đảo': '🏝️',
  'bãi biển': '🏖️',
  'sa mạc': '🏜️',
  'cát': '🏜️',
  'đá': '🗿',
  'đất': '🌍',
  'bầu trời': '🌤️',
  'mây': '☁️',
  'mưa': '🌧️',
  'tuyết': '❄️',
  'gió': '🌬️',
  'bão': '⛈️',
  'sấm': '⛈️',
  'sét': '⚡',
  'cầu vồng': '🌈',
  'mặt trời': '☀️',
  'mặt trăng': '🌙',
  'sao': '⭐',
  'ngôi sao': '⭐',
  'thời tiết': '🌦️',
  'lửa': '🔥',
  'khói': '💨',
  'băng': '🧊',
  'sóng': '🌊',
  'trái đất': '🌍',
  'thế giới': '🌍',
  'hành tinh': '🪐',
  'vũ trụ': '🌌',
  'không khí': '💨',
  'môi trường': '🌿',
  'thiên nhiên': '🍃',
  'ô nhiễm': '🏭',
  'mùa': '🍂',
  'mùa xuân': '🌸',
  'mùa hè': '☀️',
  'mùa thu': '🍂',
  'mùa đông': '❄️',
  'thành phố': '🏙️',
  'thị trấn': '🏘️',
  'làng': '🏘️',
  'quê': '🏡',
  'đất nước': '🌍',
  'quốc gia': '🌍',
  'thủ đô': '🌆',
  'chợ': '🏪',
  'cửa hàng': '🏪',
  'siêu thị': '🛒',
  'nhà hàng': '🍽️',
  'quán ăn': '🍽️',
  'khách sạn': '🏨',
  'bệnh viện': '🏥',
  'ngân hàng': '🏦',
  'bưu điện': '📮',
  'công viên': '🌳',
  'sân bay': '🛫',
  'nhà ga': '🚉',
  'bến xe': '🚌',
  'nhà máy': '🏭',
  'văn phòng': '🏢',
  'công ty': '🏬',
  'bảo tàng': '🏛️',
  'nhà thờ': '⛪',
  'chùa': '🏯',
  'rạp chiếu phim': '🎬',
  'sân vận động': '🏟️',
  'sở thú': '🦁',
  'cầu': '🌉',
  'con đường': '🛣️',
  'đường phố': '🚧',
  'lối đi': '🛤️',
  'góc': '📐',
  'nơi': '📍',
  'địa điểm': '📍',
  'biên giới': '🛂',
  'nông trại': '🚜',
  'cánh đồng': '🌾',
  'trang trại': '🚜',
  'thang máy': '🏢',
  'lối vào': '🚪',
  'xe': '🚗',
  'ô tô': '🚗',
  'xe hơi': '🚗',
  'xe máy': '🏍️',
  'xe đạp': '🚲',
  'xe buýt': '🚌',
  'xe tải': '🚚',
  'tàu': '🚆',
  'tàu hỏa': '🚆',
  'tàu thủy': '🚢',
  'thuyền': '⛵',
  'máy bay': '✈️',
  'trực thăng': '🚁',
  'tên lửa': '🚀',
  'taxi': '🚕',
  'cứu thương': '🚑',
  'phương tiện': '🚙',
  'giao thông': '🚦',
  'vé': '🎫',
  'hành khách': '🚌',
  'hộ chiếu': '🛂',
  'va li': '🧳',
  'chuyến bay': '✈️',
  'chuyến đi': '🧳',
  'du lịch': '🧳',
  'bản đồ': '🗺️',
  'máy tính': '💻',
  'điện thoại': '📱',
  'bàn phím': '⌨️',
  'màn hình': '🖥️',
  'chuột máy tính': '🖱️',
  'máy in': '🖨️',
  'máy ảnh': '📷',
  'tivi': '📺',
  'ti vi': '📺',
  'radio': '📻',
  'internet': '🌐',
  'trang web': '🌐',
  'phần mềm': '💻',
  'ứng dụng': '📱',
  'dữ liệu': '📊',
  'mạng': '🌐',
  'công nghệ': '📱',
  'robot': '🤖',
  'trí tuệ nhân tạo': '🤖',
  'thuật toán': '🧮',
  'điện': '🔌',
  'pin': '🔋',
  'động cơ': '⚙️',
  'máy móc': '⚙️',
  'máy': '⚙️',
  'dụng cụ': '🧰',
  'thiết bị': '🧰',
  'công cụ': '🔧',
  'kim loại': '🔩',
  'nhựa': '🧴',
  'gỗ': '🪵',
  'thủy tinh': '🥛',
  'vải': '🧵',
  'chất liệu': '🧵',
  'tiền': '💰',
  'tiền bạc': '💰',
  'giá': '🏷️',
  'giá cả': '🏷️',
  'hóa đơn': '🧾',
  'thẻ': '💳',
  'lãi': '📈',
  'lợi nhuận': '📈',
  'vốn': '💰',
  'thuế': '🧾',
  'kinh doanh': '💼',
  'công việc': '💼',
  'nghề': '💼',
  'lương': '💵',
  'khoản vay': '🏦',
  'tiết kiệm': '🐖',
  'đầu tư': '📈',
  'thị trường': '📊',
  'kinh tế': '📊',
  'chi phí': '💸',
  'giải thưởng': '🏅',
  'quà': '🎁',
  'sức khỏe': '💗',
  'thuốc': '💊',
  'bệnh': '🦠',
  'bệnh nhân': '🤒',
  'đau': '🤕',
  'sốt': '🤒',
  'ho': '😷',
  'vết thương': '🩹',
  'tiêm': '💉',
  'khỏe': '💪',
  'mệt': '😩',
  'buồn': '😢',
  'vui': '😀',
  'hạnh phúc': '😀',
  'giận': '😠',
  'tức giận': '😠',
  'sợ': '😨',
  'sợ hãi': '😨',
  'lo lắng': '😰',
  'ngạc nhiên': '😲',
  'xấu hổ': '😳',
  'tự hào': '😌',
  'yêu': '❤️',
  'thích': '👍',
  'ghét': '👎',
  'cười': '😂',
  'khóc': '😭',
  'mỉm cười': '🙂',
  'ngủ': '😴',
  'thức dậy': '⏰',
  'đói': '🤤',
  'khát': '🥤',
  'no': '😋',
  'bình tĩnh': '🧘',
  'thư giãn': '🛀',
  'hào hứng': '🤩',
  'tò mò': '🔍',
  'thoải mái': '🛋️',
  'dũng cảm': '🦁',
  'lười': '🦥',
  'chăm chỉ': '💪',
  'thông minh': '🦉',
  'tốt bụng': '😇',
  'lịch sự': '🙇',
  'thô lỗ': '😤',
  'thân thiện': '🤗',
  'cô đơn': '🧍',
  'ăn': '🍽️',
  'uống': '🥤',
  'nấu': '👨‍🍳',
  'nấu ăn': '👨‍🍳',
  'đi': '🚶',
  'đi bộ': '🚶',
  'chạy': '🏃',
  'nhảy': '🤸',
  'bơi': '🏊',
  'bay': '🕊️',
  'lái xe': '🚗',
  'đi xe': '🚴',
  'leo': '🧗',
  'ngồi': '💺',
  'đứng': '🧍',
  'nằm': '🛏️',
  'nói': '🗨️',
  'nói chuyện': '🗨️',
  'hỏi': '❓',
  'trả lời': '💬',
  'nghe': '👂',
  'lắng nghe': '👂',
  'nhìn': '👀',
  'xem': '📺',
  'đọc': '📖',
  'viết': '✍️',
  'vẽ': '🎨',
  'hát': '🎤',
  'múa': '💃',
  'nhảy múa': '💃',
  'chơi': '🧸',
  'học': '📚',
  'dạy': '👩‍🏫',
  'làm việc': '💼',
  'nghỉ': '🏖️',
  'mua': '🛒',
  'bán': '🏷️',
  'trả': '💵',
  'cho': '🎁',
  'nhận': '📥',
  'gửi': '📤',
  'mang': '🧳',
  'lấy': '✋',
  'đưa': '🤝',
  'mượn': '🤲',
  'giúp': '🤝',
  'giúp đỡ': '🤝',
  'mở': '🚪',
  'đóng': '🚪',
  'bắt đầu': '▶️',
  'kết thúc': '🏁',
  'dừng': '⏹️',
  'chờ': '⏳',
  'đợi': '⏳',
  'tìm': '🔍',
  'tìm kiếm': '🔍',
  'tìm thấy': '🔎',
  'mất': '❌',
  'quên': '💭',
  'nhớ': '🧠',
  'nghĩ': '💭',
  'suy nghĩ': '💭',
  'hiểu': '💡',
  'biết': '🧠',
  'tin': '🙏',
  'chọn': '☑️',
  'quyết định': '⚖️',
  'thay đổi': '🔄',
  'sửa': '🛠️',
  'sửa chữa': '🛠️',
  'xây': '🏗️',
  'xây dựng': '🏗️',
  'tạo': '✨',
  'làm': '🔧',
  'dùng': '🔧',
  'sử dụng': '🔧',
  'cắt': '✂️',
  'rửa': '🧼',
  'lau': '🧹',
  'dọn': '🧹',
  'nấu nướng': '🍳',
  'trồng': '🌱',
  'hái': '🍎',
  'đếm': '🧮',
  'đo': '📏',
  'vẽ tranh': '🎨',
  'chụp ảnh': '📸',
  'gọi': '📞',
  'gọi điện': '📞',
  'nhắn tin': '💬',
  'tải xuống': '⬇️',
  'tải lên': '⬆️',
  'lưu': '💾',
  'in': '🖨️',
  'dịch': '🔤',
  'giải thích': '🧑‍🏫',
  'mô tả': '🖊️',
  'so sánh': '⚖️',
  'kiểm tra': '🔍',
  'thử': '🧪',
  'luyện tập': '💪',
  'thi': '📝',
  'thắng': '🏆',
  'thua': '📉',
  'đánh': '⚔️',
  'bảo vệ': '🛡️',
  'cứu': '🛟',
  'trốn': '🏃',
  'trốn tránh': '🙅',
  'đến': '🛬',
  'rời': '👋',
  'về': '↩️',
  'trở lại': '↩️',
  'ở lại': '🏠',
  'thăm': '🚪',
  'mời': '💌',
  'gặp': '🤝',
  'tham gia': '🤝',
  'chia sẻ': '🤝',
  'hứa': '🤞',
  'cảm ơn': '🙏',
  'xin lỗi': '😔',
  'chào': '👋',
  'tạm biệt': '👋',
  'khám phá': '🔎',
  'phát minh': '💡',
  'phát hiện': '🔎',
  'tăng': '📈',
  'giảm': '📉',
  'cải thiện': '📈',
  'lặp lại': '🔁',
  'tiếp tục': '▶️',
  'hoàn thành': '✔️',
  'bóng': '⚽',
  'quả bóng': '⚽',
  'bóng đá': '⚽',
  'bóng rổ': '🏀',
  'bóng chuyền': '🏐',
  'cầu lông': '🏸',
  'tennis': '🎾',
  'thể thao': '⚽',
  'trò chơi': '🎮',
  'đồ chơi': '🧸',
  'búp bê': '🧸',
  'nhạc': '🎵',
  'âm nhạc': '🎵',
  'bài hát': '🎵',
  'nhạc cụ': '🎸',
  'đàn': '🎸',
  'piano': '🎹',
  'trống': '🥁',
  'sáo': '🎶',
  'phim': '🎬',
  'sân khấu': '🎭',
  'buổi hòa nhạc': '🎤',
  'lễ hội': '🎊',
  'tiệc': '🎉',
  'sinh nhật': '🎂',
  'kỳ nghỉ': '🏖️',
  'sở thích': '🎨',
  'câu đố': '❔',
  'tranh': '🖼️',
  'bức tranh': '🖼️',
  'ảnh': '📸',
  'bức ảnh': '📸',
  'truyện': '📖',
  'truyện tranh': '🦸',
  'cuộc thi': '🏆',
  'chiến thắng': '🏆',
  'huy chương': '🏅',
  'cúp': '🏆',
  'thời gian': '⏰',
  'giờ': '🕐',
  'phút': '⏱️',
  'giây': '⏱️',
  'ngày': '📅',
  'tuần': '📆',
  'tháng': '🗓️',
  'năm': '🗓️',
  'thế kỷ': '🕰️',
  'hôm nay': '📅',
  'ngày mai': '⏭️',
  'hôm qua': '⏮️',
  'sáng': '🌅',
  'trưa': '☀️',
  'chiều': '🌇',
  'tối': '🌆',
  'đêm': '🌙',
  'quá khứ': '⏪',
  'tương lai': '🔮',
  'hiện tại': '⏺️',
  'màu đỏ': '🟥',
  'màu xanh dương': '🟦',
  'màu xanh lá': '🟩',
  'màu vàng': '🟨',
  'màu tím': '🟪',
  'màu nâu': '🟫',
  'màu đen': '⬛',
  'màu trắng': '⬜',
  'màu cam': '🟧',
  'màu hồng': '🌸',
  'màu xám': '🌫️',
  'màu sắc': '🎨',
  'chiến tranh': '⚔️',
  'hòa bình': '🕊️',
  'chính phủ': '🏛️',
  'luật': '⚖️',
  'quyền': '✊',
  'tự do': '🕊️',
  'văn hóa': '🏮',
  'tôn giáo': '🙏',
  'lịch trình': '📅',
  'kế hoạch': '📋',
  'dự án': '📊',
  'báo cáo': '📄',
  'thông tin': 'ℹ️',
  'tin tức': '📺',
  'tin nhắn': '💬',
  'thư điện tử': '📧',
  'cuộc họp': '👥',
  'hội nghị': '🎤',
  'ý tưởng': '💡',
  'vấn đề': '❓',
  'kết quả': '📊',
  'nguyên nhân': '🧩',
  'lý do': '🧩',
  'mục đích': '🎯',
  'mục tiêu': '🎯',
  'kỹ năng': '🎯',
  'kinh nghiệm': '🧗',
  'cơ hội': '🚪',
  'nguy hiểm': '⚠️',
  'an toàn': '🛡️',
  'bí mật': '🤐',
  'sự thật': '💯',
  'lỗi': '❌',
  'lỗi sai': '❌',
  'chất lượng': '✨',
  'số lượng': '🔢',
  'kích thước': '📏',
  'chiều cao': '📏',
  'chiều dài': '📏',
  'khoảng cách': '🛣️',
  'trọng lượng': '⚖️',
  'nhiệt độ': '🌡️',
  'tốc độ': '💨',
  'hình dạng': '🔺',
  'hình tròn': '⭕',
  'hình vuông': '🟥',
  'hình tam giác': '🔺',
  'hình chữ nhật': '▭',
  'đường thẳng': '➖',
  'phần trăm': '💯',
  'một nửa': '🌗',
  'đôi': '✌️',
  'nhóm': '👥',
  'hệ thống': '⚙️',
  'cấu trúc': '🏗️',
  'phương pháp': '📐',
  'quy tắc': '📋',
  'thói quen': '🔁',
  'truyền thống': '🏮',
  'lễ': '🎊',
  'kho báu': '💎',
  'vàng': '🥇',
  'bạc': '🥈',
  'thanh toán': '💳',
  'tài khoản': '🏦',
  'giao dịch': '💳',
  'chuyển khoản': '💸',
  'tiền mặt': '💵',
  'tiền gửi': '🏦',
  'rút tiền': '🏧',
  'lãi suất': '📈',
  'tỷ giá': '💱',
  'ngoại tệ': '💱',
  'thẻ tín dụng': '💳',
  'tín dụng': '💳',
  'cho vay': '🏦',
  'thế chấp': '🏠',
  'nợ xấu': '📉',
  'bảo hiểm': '🛡️',
  'rủi ro': '⚠️',
  'cổ phiếu': '📊',
  'trái phiếu': '📜',
  'chứng khoán': '📊',
  'quỹ': '💰',
  'dòng tiền': '💵',
  'doanh thu': '📈',
  'ngân sách': '💰',
  'kế toán': '🧮',
  'kiểm toán': '🔍',
  'sổ sách': '📒',
  'giấy tờ': '📄',
  'chi nhánh': '🏦',
  'phí dịch vụ': '🏷️',
  'hoàn tiền': '↩️',
  'mô hình': '📐',
  'học máy': '🤖',
  'mạng nơ ron': '🧠',
  'huấn luyện': '🏋️',
  'mô phỏng': '🎮',
  'nhận dạng': '🔍',
  'phân loại': '🗂️',
  'dự đoán': '🔮',
  'xử lý': '⚙️',
  'tự động': '🤖',
  'tự động hóa': '🤖',
  'điều khiển': '🎛️',
  'cảm biến': '📡',
  'giám sát': '👁️',
  'đám mây': '☁️',
  'máy chủ': '🖥️',
  'cơ sở dữ liệu': '🗄️',
  'phần cứng': '🔩',
  'mã nguồn': '💻',
  'lập trình': '💻',
  'giao diện': '🖥️',
  'bộ nhớ': '💾',
  'vi xử lý': '🔩',
  'cánh tay robot': '🦾',
  'băng tải': '📦',
  'cơ cấu': '⚙️',
  'truyền động': '⚙️',
  'lắp ráp': '🔧',
  'vận hành': '⚙️',
  'bảo trì': '🔧',
  'bảo dưỡng': '🔧',
  'sự cố': '💥',
  'cảnh báo': '⚠️',
  'khẩn cấp': '🚨',
  'thử nghiệm': '🧪',
  'kiểm thử': '🧪',
  'lắp đặt': '🔧',
  'hiệu chuẩn': '📏',
  'độ chính xác': '🎯',
  'quản lý': '🧑‍💼',
  'phát triển': '📈',
  'đánh giá': '⭐',
  'dịch vụ': '🛎️',
  'sản phẩm': '📦',
  'doanh nghiệp': '🏢',
  'chiến lược': '♟️',
  'quy trình': '📋',
  'tiêu chuẩn': '📏',
  'hiệu quả': '⚡',
  'năng suất': '📈',
  'cạnh tranh': '🏆',
  'hợp đồng': '📜',
  'thỏa thuận': '🤝',
  'đàm phán': '🤝',
  'tài liệu': '📄',
  'hồ sơ': '🗂️',
  'giấy phép': '📜',
  'chứng chỉ': '🎓',
  'trách nhiệm': '⚖️',
  'nghĩa vụ': '⚖️',
  'chính sách': '📜',
  'pháp luật': '⚖️',
  'quy định': '📋',
  'vi phạm': '🚫',
  'xử phạt': '⚖️',
  'thanh tra': '🔍',
  'nhân sự': '👥',
  'tuyển dụng': '🙋',
  'đào tạo': '🧑‍🏫',
  'lương thưởng': '💵',
  'nghỉ phép': '🏖️',
  'khảo sát': '📋',
  'phân tích': '📊',
  'kết luận': '✔️',
  'bằng chứng': '🔍',
  'lý thuyết': '📚',
  'thực nghiệm': '🧪',
  'khái niệm': '💭',
  'định nghĩa': '📖',
  'ví dụ': '📝',
  'hậu quả': '💥',
  'ảnh hưởng': '💥',
  'xu hướng': '📈',
  'tỷ lệ': '💯',
  'số liệu': '📊',
  'biểu đồ': '📊',
  'nguồn gốc': '🌱',
  'quan điểm': '💬',
  'lập luận': '🗣️',
  'giả thuyết': '💭',
  'chủ đề': '📌',
  'nội dung': '📄',
  'bài viết': '📝',
  'luận văn': '📜',
  'tóm tắt': '📋',
  'bao nhiêu': '🔢',
  'địa chỉ': '📍',
  'số điện thoại': '📱',
  'ngày sinh': '🎂',
  'họ tên': '📝',
  'gặp gỡ': '🤝',
  'hẹn gặp': '📅',
  'đặt phòng': '🏨',
  'đặt bàn': '🍽️',
  'thực đơn': '📋',
  'món ăn': '🍽️',
  'đồ uống': '🥤',
  'nhà thuốc': '💊',
  'khám bệnh': '👨‍⚕️',
  'thuốc men': '💊',
  'mua sắm': '🛒',
  'giặt giũ': '🧺',
  'thể dục': '🏃',
  'nghỉ ngơi': '🛀',
  'đi lại': '🚶',
  'giày dép': '👟',
  'bàn ghế': '🪑',
  'đồ đạc': '🛋️',
  'gia vị': '🧂',
  'bữa cơm': '🍚',
  'chào hỏi': '👋',
  'chúc mừng': '🎉',
  'sinh hoạt': '🏡',
  'thời khóa biểu': '📅',
  'giờ giấc': '⏰',
  'thời tiết hôm nay': '🌦️',
  'mười': '🔟',
  'hai mươi': '🔢',
  'một trăm': '💯',
  'một nghìn': '🔢',
  'một tỷ': '🔢',
  'một phần tư': '🕒',
  'đúng': '✅',
  'sai': '❌',
  'xử lý thời gian thực': '⚙️'
};

// Chữ đứng đầu chỉ để phân loại, bỏ đi để lấy lõi nghĩa.
var LOAI_TU = [
  'con', 'cái', 'quả', 'trái', 'chiếc', 'cây', 'bông', 'tấm', 'ngôi', 'căn',
  'ly', 'cốc', 'đôi', 'bộ', 'món', 'chai', 'lọ', 'tờ', 'quyển', 'cuốn',
  'sự', 'việc', 'cuộc', 'nỗi', 'niềm', 'người', 'kẻ', 'nhà', 'thợ', 'đồ'
];

var SHEET_BO_QUA = { LEADERBOARD: true, STATS: true, LOG: true, LINKS: true, CONFIG: true, STARTERS: true };

var CUM_NHIEU_TIENG = null;

/**
 * Chỉ cụm từ hai tiếng trở lên mới được khớp vào giữa một nghĩa dài.
 * Tiếng Việt ghép âm tiết, khoá một tiếng lọt vào giữa từ ghép là ra nghĩa khác
 * hẳn: "ở nước ngoài" thành nước uống, "hành vi" thành củ hành, "sự công nhận"
 * thành con công. Khoá một tiếng vì vậy chỉ dùng khi trùng khít cả vế nghĩa.
 */
function cumNhieuTieng_() {
  if (CUM_NHIEU_TIENG) return CUM_NHIEU_TIENG;
  var keys = [];
  for (var k in NGHIA_SANG_HINH) {
    if (k.indexOf(' ') >= 0) keys.push(k);
  }
  keys.sort(function (a, b) { return b.length - a.length; });
  CUM_NHIEU_TIENG = keys;
  return keys;
}

function chuanHoa_(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/\([^)]*\)/g, ' ')
    .replace(/[.!?"'\u201c\u201d]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function traNghia_(text) {
  if (!text) return '';
  if (Object.prototype.hasOwnProperty.call(NGHIA_SANG_HINH, text)) return NGHIA_SANG_HINH[text];
  for (var i = 0; i < LOAI_TU.length; i += 1) {
    var dau = LOAI_TU[i] + ' ';
    if (text.indexOf(dau) === 0) {
      var con = text.slice(dau.length).trim();
      if (Object.prototype.hasOwnProperty.call(NGHIA_SANG_HINH, con)) return NGHIA_SANG_HINH[con];
    }
  }
  var padded = ' ' + text + ' ';
  var cum = cumNhieuTieng_();
  for (var j = 0; j < cum.length; j += 1) {
    if (padded.indexOf(' ' + cum[j] + ' ') >= 0) return NGHIA_SANG_HINH[cum[j]];
  }
  return '';
}

function chonHinh_(vi, answer) {
  var senses = chuanHoa_(vi).split(/[;,\/|]+/);
  for (var i = 0; i < senses.length; i += 1) {
    var hit = traNghia_(senses[i].trim());
    if (hit) return hit;
  }
  var en = chuanHoa_(answer).replace(/^(to|the|a|an)\s+/, '');
  if (Object.prototype.hasOwnProperty.call(ANH_SANG_HINH, en)) return ANH_SANG_HINH[en];
  return '';
}

function dienCotHinh() {
  var ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  var sheets = ss.getSheets();
  var tongMoi = 0;
  var dong = [];

  for (var s = 0; s < sheets.length; s += 1) {
    var sheet = sheets[s];
    var ten = sheet.getName();
    if (SHEET_BO_QUA[ten.toUpperCase()]) continue;

    var lastRow = sheet.getLastRow();
    var lastCol = Math.max(sheet.getLastColumn(), 6);
    if (lastRow < 2) continue;

    var headers = sheet.getRange(1, 1, 1, lastCol).getDisplayValues()[0];
    var cot = detectColumns_(headers);
    var cotHinh = cot.image >= 0 ? cot.image + 1 : 6;

    if (cot.image < 0) sheet.getRange(1, cotHinh).setValue('HÌNH');

    var soDong = lastRow - 1;
    var values = sheet.getRange(2, 1, soDong, lastCol).getDisplayValues();
    var oHinh = sheet.getRange(2, cotHinh, soDong, 1);
    var congThuc = oHinh.getFormulas();
    var giaTri = oHinh.getValues();

    var moi = [];
    var khoa = [];
    var them = 0;
    var soAnhTrongO = 0;

    for (var r = 0; r < soDong; r += 1) {
      var ct = congThuc[r][0];
      var gt = giaTri[r][0];

      // Ảnh chèn thẳng vào ô (Chèn > Hình ảnh trong ô) về đây là một đối tượng,
      // không phải chuỗi. Ghi đè lên là mất ảnh, nên khoá hẳn dòng đó lại.
      if (gt && typeof gt === 'object') {
        moi.push(['']);
        khoa.push(true);
        soAnhTrongO += 1;
        continue;
      }
      // Công thức (ví dụ =IMAGE("...")) hiển thị ra chuỗi rỗng, nhìn qua tưởng ô
      // trống. Phải đọc riêng công thức mới biết là ô đã có nội dung.
      if (ct) { moi.push([ct]); khoa.push(false); continue; }
      // Giữ nguyên si giá trị đang có, không chuẩn hoá khoảng trắng gì cả.
      if (String(gt).trim()) { moi.push([gt]); khoa.push(false); continue; }

      var vi = clean_(values[r][cot.vi]);
      var answer = clean_(values[r][cot.answer]);
      var hinh = (vi && answer) ? chonHinh_(vi, answer) : '';
      if (hinh) them += 1;
      moi.push([hinh]);
      khoa.push(false);
    }

    // Ghi theo từng đoạn liền mạch, nhảy qua các dòng đang giữ ảnh trong ô.
    var dau = 0;
    while (dau < soDong) {
      if (khoa[dau]) { dau += 1; continue; }
      var cuoi = dau;
      while (cuoi + 1 < soDong && !khoa[cuoi + 1]) cuoi += 1;
      sheet.getRange(2 + dau, cotHinh, cuoi - dau + 1, 1).setValues(moi.slice(dau, cuoi + 1));
      dau = cuoi + 1;
    }

    tongMoi += them;
    dong.push(ten + ': thêm ' + them + ' hình (cột ' + cotHinh + ')'
      + (soAnhTrongO ? ', giữ nguyên ' + soAnhTrongO + ' ảnh chèn trong ô' : ''));
  }

  var ketQua = dong.join('\n') + '\n\nTỔNG CỘNG THÊM MỚI: ' + tongMoi;
  Logger.log(ketQua);
  return ketQua;
}

/**
 * Soát cột HÌNH và chỉ ra những ô ứng dụng SẼ KHÔNG hiện được.
 *
 * Cần có vì khi ảnh hỏng, ứng dụng lặng lẽ giấu khung đi chứ không báo gì —
 * nhìn vào bảng tính thấy ô có nội dung, mở app lại chẳng thấy hình, không biết
 * đường nào mà lần. Dán link Drive hàng loạt thì càng phải soát.
 *
 * Luật ở đây chép đúng theo hàm imageSource trong script.js.
 */
function kiemTraCotHinh() {
  var ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  var sheets = ss.getSheets();
  var loi = [];
  var demEmoji = 0;
  var demLink = 0;

  for (var s = 0; s < sheets.length; s += 1) {
    var sheet = sheets[s];
    var ten = sheet.getName();
    if (SYSTEM_SHEETS[ten.toUpperCase()]) continue;

    var lastRow = sheet.getLastRow();
    if (lastRow < 2) continue;
    var lastCol = Math.max(sheet.getLastColumn(), 6);
    var cot = detectColumns_(sheet.getRange(1, 1, 1, lastCol).getDisplayValues()[0]);
    if (cot.image < 0) continue;

    var duLieu = sheet.getRange(2, 1, lastRow - 1, lastCol).getDisplayValues();
    for (var r = 0; r < duLieu.length; r += 1) {
      var o = clean_(duLieu[r][cot.image]);
      if (!o) continue;
      var tu = clean_(duLieu[r][cot.answer]);
      var viTri = ten + '!' + (r + 2) + ' (' + tu + ')';
      var vd = o.length > 60 ? o.slice(0, 60) + '…' : o;

      if (/^http:\/\//i.test(o)) {
        loi.push(viTri + ': dùng http, ứng dụng Android chặn — phải là https · ' + vd);
        continue;
      }
      if (/^https:\/\//i.test(o)) {
        if (o.indexOf('drive.google.com/drive/folders/') >= 0) {
          loi.push(viTri + ': đây là link THƯ MỤC Drive, phải là link từng tệp · ' + vd);
          continue;
        }
        var m = o.match(/drive\.google\.com\/(?:file\/d\/|open\?id=|uc\?(?:[^#]*&)?id=)([A-Za-z0-9_-]+)/);
        if (o.indexOf('drive.google.com') >= 0 && !m) {
          loi.push(viTri + ': link Drive không rút được mã tệp · ' + vd);
          continue;
        }
        if (m) {
          try {
            var quyen = DriveApp.getFileById(m[1]).getSharingAccess();
            if (quyen !== DriveApp.Access.ANYONE && quyen !== DriveApp.Access.ANYONE_WITH_LINK) {
              loi.push(viTri + ': tệp Drive chưa mở công khai, máy người học sẽ không tải được · ' + vd);
              continue;
            }
          } catch (err) {
            loi.push(viTri + ': không mở được tệp Drive (sai mã hoặc đã xoá) · ' + vd);
            continue;
          }
        }
        demLink += 1;
        continue;
      }
      // Không phải link: mã tệp Drive trần, hoặc emoji. Dài quá thì ứng dụng bỏ qua.
      if (/^[A-Za-z0-9_-]{20,80}$/.test(o)) { demLink += 1; continue; }
      if (o.length > 12) {
        loi.push(viTri + ': dài ' + o.length + ' ký tự, không phải link cũng không phải emoji — ứng dụng sẽ bỏ qua · ' + vd);
        continue;
      }
      demEmoji += 1;
    }
  }

  var ketQua = 'Emoji hợp lệ: ' + demEmoji + '\nLink ảnh hợp lệ: ' + demLink
    + '\nÔ có vấn đề: ' + loi.length
    + (loi.length ? '\n\n' + loi.slice(0, 200).join('\n') : '')
    + (loi.length > 200 ? '\n… và ' + (loi.length - 200) + ' ô nữa' : '');
  Logger.log(ketQua);
  return ketQua;
}
